stages:
  - build
  - test
  - publish

.build:
  stage: build
  variables:
    ARCH: armv7hl
    SFOS_VERSION: "4.4.0.58"
  image: coderus/sailfishos-platform-sdk:${SFOS_VERSION}
  artifacts:
    paths:
      - "output/*"
  script:
    - mkdir output
    - mkdir ~/build
    - cp -r * ~/build
    - pushd ~/build
    - mb2 -t SailfishOS-$SFOS_VERSION-$ARCH build
    - popd
    - cp -v ~/build/RPMS/* output

build_armv7hl:
  extends: .build

build_i486:
  extends: .build
  variables:
    ARCH: i486

build_aarch64:
  extends: .build
  variables:
    ARCH: aarch64

test:validate-rpms:
  stage: test
  image: registry.gitlab.com/whisperfish/sailo-rs/rpm-validator:latest
  allow_failure: true
  needs:
    - build_armv7hl
    - build_i486
    - build_aarch64
  script:
    - rpmvalidation.sh output/*.rpm
