stages:
  - build
  - publish

.build:
  stage: build
  variables:
    ARCH: armv7hl
    SFOS_VERSION: "3.4.0.24"
  allow_failure: true
  image: "coderus/sailfishos-platform-sdk:${SFOS_VERSION}"
  artifacts:
    paths:
      - "output/*"
  script:
    - mkdir output
    - mkdir ~/build
    - cp -r * ~/build
    - pushd ~/build
    - mb2 -t SailfishOS-$SFOS_VERSION-$ARCH build
    - popd
    - cp -v ~/build/RPMS/* output

  only:
    - merge_requests
    - tags
  tags:
    - docker

build_armv7hl:
  extends: .build

build_i486:
  extends: .build
  variables:
    ARCH: i486

build_aarch64:
  extends: .build
  variables:
    ARCH: aarch64

publish:
    image: inetprocess/gitlab-release
    stage: publish
    needs:
      - build_armv7hl
      - build_i486
      - build_aarch64
    only:
      - tags
    script:
      - gitlab-release --message 'Release $CI_COMMIT_TAG' output/*
